### ISSUE TITLE
Package.appxmanifest is not valid. Attribute "ForegroundText" is missing". 

### ISSUE THREAD

**Issue by chrwick** [ms-iot/virtual-shields-universal#12]
Trying to open any XAML file within the "shield" project within VS15RC with the XAML designer results in the following error message which states that the manifest is not valid because it would be missing the attribute "ForegroundText" which must be valid according to the schema:

```
System.Exception
Das Manifest des Appx-Pakets ist ungültig.

Fehler 0xC00CE020: Überprüfungsfehler bei App-Manifest: Das App-Manifest muss gemäß Schema gültig sein: Zeile 20, Spalte 8, Ursache: Erforderliches Attribut 'ForegroundText' fehlt.
.
   at Microsoft.VisualStudio.DesignTools.HostUtility.Platform.AppContainerProcessDomainFactory.CreateDesignerProcess(String applicationPath, String clientPort, Uri hostUri, IDictionary environmentVariables, Int32& processId, Object& processData)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Primitives.ProcessDomainFactory.ProcessIsolationDomain..ctor(ProcessDomainFactory factory, IIsolationBoundary boundary, AppDomainSetup appDomainInfo, PlatformIdentifier platformIdentifier, String identifier, String baseDirectory)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Primitives.ProcessDomainFactory.CreateIsolationDomain(IIsolationBoundary boundary)
   at Microsoft.VisualStudio.DesignTools.HostUtility.Platform.AppContainerProcessDomainFactory.CreateIsolationDomain(IIsolationBoundary boundary)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Primitives.IsolationBoundary.Initialize()
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.Primitives.IsolationBoundary.CreateInstance[T](Type type)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.IsolatedObjectFactory.Initialize()
   at Microsoft.VisualStudio.DesignTools.DesignerHost.Services.VSIsolationService.CreateObjectFactory(IIsolationTarget isolationTarget, IObjectCatalog catalog)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.IsolationService.CreateLease(IIsolationTarget isolationTarget)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.IsolatedDesignerService.CreateLease(IIsolationTarget isolationTarget, CancellationToken cancelToken, DesignerServiceEntry& entry, IServiceProvider serviceOverrides)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.IsolatedDesignerService.IsolatedDesignerView.CreateDesignerViewInfo(CancellationToken cancelToken)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.IsolatedTaskScheduler.InvokeWithCulture[T](CultureInfo culture, Func`2 func, CancellationToken cancelToken)
   at Microsoft.VisualStudio.DesignTools.DesignerContract.Isolation.IsolatedTaskScheduler.<>c__DisplayClass4`1.<StartTask>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()


```

However, I am able to build and deploy the app to a device or the emulator.

**Comment by JimGaleForce** [comment]
This is likely a version issue or difference... what versions do you have of the following: Windows OS, Windows SDK (different version likely), VS (need a number).
Thanks,

**Comment by chrwick** [comment]
Windows OS: Windows 10 Pro Technical Preview Build 10041
Windows SDK: Version 10.0.10069 (was installed as part of VS15RC Installation)
Visual Studio: 14.0.22823.1 D14REL

**Comment by JimGaleForce** [comment]
Ok, the //build OS version is 10074 (SDK is still 10069)... if you can Windows Upgrade to that, it should match all the docs we have.

**Comment by chrwick** [comment]
Upgrade from 10041 to 10074 was not possible for me, because I installed it in a VHD file. 
The update process to 10074 gives an error that "Windows 10 cannot be installed in a virtual container file" and then stops.

So I reinstalled Windows 10 on a partition an reinstalled everything again.
The upgrade from 10041 to 10074 went ok. 

Now the XAML file can be opened in design view.

I think you can close the issue. Most things seem to be still in preview phase with bugs.

**Comment by JimGaleForce** [comment]
Yes, sounds good - thanks!
